### PR TITLE
Added Uniform Cost Search

### PR DESCRIPTION
**Pull request by parmar532**
This algorithm is used as a base for the famous algorithm A* search which is based on heuristics and ucs, to find the optimal path in the graph, also a variant of Djkstra's Algorithm.

Hoping to merge for Hactoberfest-2020 !!
Also, mark hacktoberfest-2020 label if feasible, i am beginner to github.

### CODE REVIEW

**Comment by Iltwats** [comment]
Can You add comment lines to explain your approach in program.

**Comment by Coder481** [comment]
Try to explain the program's components through comments...

**Comment by Iltwats** [comment]
You have 3 days before this PR will be marked as spam.

**Comment by parmar532** [comment]
> You have 3 days before this PR will be marked as spam.

**Comment by parmar532** [comment]
Added the comment, please re-verify.
Thank you for bringing in my notice to add comments to code.

Also please do let me know if other changes are required to be done or not, and don't forget to add the label, "hacktoberfest-2020 accepted" if it is merged,

**Comment by Iltwats** [comment]
We have labelled this repo for hacktoberfest, so it is not necessary yo add hacktoberfest-accepted label.

**Pull request merged**
