### PR TITLE
#27

### PR DESCRIPTION
**Pull request by aasthajain12**

### CODE REVIEW

**Comment by Iltwats** [comment]
@aasthajain12 can you provide information about the code or which issue are you referring?

**Comment by aasthajain12** [comment]
I am referring the issue for Queue Implementation(#27). I have written the
code for Implementation of queue using single stack in C++.

**Comment by aasthajain12** [comment]
Could you please label my pr with  Hacktoberfest 2020 and hacktoberfest-accepted labels? In my profile it is showing contributed to invalis repository.

**Comment by Iltwats** [comment]
PR was reverted because it was put in the wrong directory.

**Pull request merged**
