### PR TITLE
Create Find Mid Point, Reverse of a linked list, Node Search,Delete R…

### PR DESCRIPTION
**Pull request by JaveedYara72**
…andom

### CODE REVIEW

**Comment by Swapnil7000** [comment]
Add the file with respective extension like .c,.cpp.Then we will merge it

**Comment by JaveedYara72** [comment]
Okay Sure.

**Comment by JaveedYara72** [comment]
Hey I Have done the Changes, Will You let me Know the Status?

**Comment by JaveedYara72** [comment]
Thank you.

**Pull request merged**
