### PR TITLE
Create Codeforces STL question

### PR DESCRIPTION
**Pull request by nirbhay55**
1600 rated question  in Codedforces

### CODE REVIEW

**Comment by Iltwats** [comment]
Please take problems from issue section, this repository is intended for dsa purpose so that people can refer it to learn.

**Comment by nirbhay55** [comment]
These question are also for practice purpopse so that after reading concepts one can practice the quality questions.

**Comment by nirbhay55** [comment]
I will also try to do the problems on issue section

**Comment by Iltwats** [comment]
> These question are also for practice purpopse so that after reading concepts one can practice the quality questions.

I merged your previous PR ,but I was objected by other maintainer regarding it.So please follow the guidelines given.

**Pull request closed without merging**
